application: danecjensen
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "15m"

handlers:
# site root
- url: /
  static_files: _site/index.html
  upload: _site/index.html
  secure: always

- url: /bio
  static_files: _site/bio.html
  upload: _site/bio.html
  secure: always

- url: /
  static_dir: _site
  secure: always
